Update transaction.py for marshmallow-3
Marshmallow v3 update forces Number to be an Integer or a Float (can no longer use 'Number')

Error message: 
AttributeError: 'Number' object has no attribute 'num_type'